default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: root
    password:
    database: ouma
    host: 127.0.0.1
    port: 3306
development:
    <<: *default

production:
    <<: *default
    database: db/production.sqlite3
    adatapter: 'postresql'
